set(VERSION 3.2)

vcpkg_fail_port_install(ON_TARGET "UWP")

set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)

# There's a 3.2 release but it was never added to the ftp
# Use a GitHub mirror instead
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO rurban/gperf
    REF v3.2
    SHA512 9373ddff2b3f631722e7dbc1ad7330466d1322ff552c4876b36b397e75b0ec5f665b3a4437ea1b7163989f8e8864007548938b0970df2b345f8ae324d3f0d91d
)

file(COPY ${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt DESTINATION ${SOURCE_PATH})
file(COPY ${CMAKE_CURRENT_LIST_DIR}/config.h.in DESTINATION ${SOURCE_PATH})

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS -DCMAKE_SYSTEM_VERSION=8.1
    OPTIONS_RELEASE -DCMAKE_INSTALL_BINDIR=tools
)

vcpkg_install_cmake()

file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug)
if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
endif()
